export enum QueryKey {
  GET_PLAN_LIST = 'GET_PLAN_LIST',
  GET_ME = 'GET_ME',
  GET_USER_BY_SLUG = 'GET_USER_BY_SLUG',
  GET_USER_BY_LIVE_SLUG = 'GET_USER_BY_LIVE_SLUG',
  GET_USER_CONFIG = 'GET_USER_CONFIG',
  GET_USER_CONFIG_BY_SLUG = 'GET_USER_CONFIG_BY_SLUG',
  GET_BALANCE = 'GET_BALANCE',
  GET_DONATION_TRANSACTION_LIST = 'GET_DONATION_TRANSACTION_LIST',
}
